### ISSUE TITLE
Headings display poorly in Firefox

### ISSUE THREAD

**Issue by jcouturier** [leemunroe/blog#1]
Always test with multiple browsers ;)

![dmftrlr](https://cloud.githubusercontent.com/assets/3639237/4221170/3895bb14-3907-11e4-8733-83ace2f1ffa0.png)

**Comment by leemunroe** [comment]
@jcouturier Wow, just came across this issue. Sorry for not noticing sooner. Tested latest Firefox and all looks to be good now. Thanks for the ping.

**Comment by jcouturier** [comment]
:thumbsup:  :smiley:
